name: Test Android

on:
  push:
    branches: [ "ci/cd" ]
  pull_request:
    branches: [ "ci/cd" ]

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temuri'
        cache: gradle
    - name: Setup gradle
      uses: gradle/gradle-build-action@v2
    - name: Build app
      run: ./gradlew assemble
      